---
abstract: 'base-class for a tcpdump like implementation'
author:
  - 'GomoR <gomor-cpan_at_gomor.org>'
build_requires: {}
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Frame-Dump
provides:
  Net::Frame::Dump:
    file: lib/Net/Frame/Dump.pm
    version: '1.14'
  Net::Frame::Dump::Offline:
    file: lib/Net/Frame/Dump/Offline.pm
  Net::Frame::Dump::Online:
    file: lib/Net/Frame/Dump/Online.pm
  Net::Frame::Dump::Online2:
    file: lib/Net/Frame/Dump/Online2.pm
  Net::Frame::Dump::Writer:
    file: lib/Net/Frame/Dump/Writer.pm
requires:
  Class::Gomor: '1.00'
  IO::Select: '0'
  Net::Frame: '0'
  Net::Pcap: '0.12'
  Time::HiRes: '0'
  perl: v5.6.1
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: '1.14'
