--- #YAML:1.0
name:               Net-Frame-Dump
version:            1.09
abstract:           base-class for a tcpdump like implementation
author:
    - GomoR <gomor-cpan_at_gomor.org>
license:            artistic
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Gomor:  1.00
    Net::Frame:    0
    Net::Pcap:     0.12
    Time::HiRes:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
